import {chromium} from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve('..');
const cfg=JSON.parse(fs.readFileSync(path.join(root,'.local/config.json'),'utf8'));
fs.mkdirSync(path.join(root,'artifacts'),{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8123');
await page.getByLabel('Access token').fill(cfg.users.operator);
await page.getByRole('button',{name:'Open workspace'}).click();
await page.getByRole('heading',{name:'Change assurance',exact:true}).waitFor();
await page.screenshot({path:path.join(root,'artifacts/dashboard-desktop.png'),fullPage:true});
await page.getByRole('button',{name:'Financial lab',exact:true}).click();
await page.getByLabel('Amount (THB)').fill('12.50');
await page.getByRole('button',{name:'Submit / replay payment'}).click();
await page.getByText('Payment committed with three balanced postings.',{exact:false}).waitFor();
await page.getByRole('button',{name:'Submit / replay payment'}).click();
await page.getByText('Existing payment returned',{exact:false}).waitFor();
await page.getByLabel('Amount (THB)').fill('99.00');
await page.getByRole('button',{name:'Submit / replay payment'}).click();
await page.getByRole('alert').filter({hasText:'different payment parameters'}).waitFor();
await page.getByRole('button',{name:'Dismiss error'}).click();
await page.getByRole('button',{name:'Changes',exact:false}).first().click();
await page.getByRole('button',{name:'Load failing fixture'}).click();
await page.getByRole('heading',{name:'Regression fixture · bad'}).waitFor();
await page.getByRole('button',{name:'Verify',exact:true}).click();
await page.getByText(/^(QUEUED|VERIFYING|BLOCKED)$/).first().waitFor();
await page.screenshot({path:path.join(root,'artifacts/change-evidence.png'),fullPage:true});
await page.getByRole('button',{name:'Overview',exact:true}).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:path.join(root,'artifacts/dashboard-mobile.png'),fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
if(overflow)throw new Error('Mobile page has horizontal overflow');
await page.setViewportSize({width:1440,height:1000});
await page.getByTitle('Sign out').click();
await page.getByLabel('Access token').fill(cfg.users.viewer);
await page.getByRole('button',{name:'Open workspace'}).click();
await page.getByRole('heading',{name:'Change assurance',exact:true}).waitFor();
await page.getByRole('button',{name:'Financial lab',exact:true}).click();
if(!await page.getByRole('button',{name:'Submit / replay payment'}).isDisabled())throw new Error('Viewer action enabled');
await browser.close();
if(errors.length)throw new Error(errors.join('\n'));
console.log('Browser journey PASS: login, finance transfer/replay/conflict, proposal/queue, mobile layout, viewer restriction.');
